#!/usr/bin/env bash
set -e

ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling1.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling1.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling2.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling2.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling3.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling3.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling4.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling4.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling5.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling5.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling6.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling6.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling7.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling7.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling8.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling8.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling9.wav -acodec pcm_s16le -ac 1 -ar 16000       /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling9.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling10.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling10.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling11.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling11.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling12.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling12.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling13.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling13.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling14.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling14.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling15.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling15.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling16.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling16.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling17.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling17.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling18.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling18.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling19.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling19.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling20.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling20.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/strugling/strugling21.wav -acodec pcm_s16le -ac 1 -ar 16000      /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_strugling21.wav


ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water1.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water1.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water2.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water2.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water3.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water3.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water4.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water4.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water5.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water5.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water6.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water6.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water7.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water7.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water8.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water8.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water9.wav   -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water9.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water10.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water10.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water11.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water11.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water12.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water12.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water13.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water13.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water14.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water14.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water15.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water15.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water16.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water16.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water17.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water17.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water18.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water18.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water19.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water19.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water20.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water20.wav
ffmpeg -i  /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/NAR_dataset/water/water21.wav  -acodec pcm_s16le -ac 1 -ar 16000 /home/mdomrachev/PycharmProjects/competitions/speech_commands/crt_competition/scripts/addit_data/16_k_add_data/16_k_water21.wav


